### PR TITLE
Convert documents to PDF

### PR DESCRIPTION
**Pull request by GoebelL**

### CODE REVIEW

**Review by chaconpiza — CHANGES_REQUESTED** [review]
Thanks for the PR,

I downloaded the file `SystemOperator.docx` but I can't open it with MS Word 2016:

```
We're sorry. We can't open SystemOperator bacause we found a problem with its contents.
The file is corrupt and cannot be opened
```

**Review by chaconpiza — APPROVED** [review]
It is ok from my point of view

- [x] Nice _Look and feel_
- [x] Different typography for Language and Metalanguage
- [x] Correct Table of contents
- [x] Correct content (But I didn't check on deep)

I have a minor proposition to discuss: _Could we add the hash of latest commit to be sure of the content in the static PDF/Word documents?_

**Comment by GoebelL** [comment]
> 
> 
> It is ok from my point of view
> 
>     * [x]  Nice _Look and feel_
> 
>     * [x]  Different typography for Language and Metalanguage
> 
>     * [x]  Correct Table of contents
> 
>     * [x]  Correct content (But I didn't check on deep)
> 
> 
> I have a minor proposition to discuss: _Could we add the hash of latest commit to be sure of the content in the static PDF/Word documents?_

Done.

**Review by chaconpiza — CHANGES_REQUESTED** [review]
Thanks for adding the hash, it looks ok.
We were ask to add this change before build pdfs:
**PR Fix Activating Additional Metrics:**  https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/cmm-documentation/pull/51
Could we merge the PR 51 first, then rebase `GoebelL-patch-2` on `master` and rebuild the Sys Operator pdf?

**Comment by GoebelL** [comment]
> 
> 
> Thanks for adding the hash, it looks ok.
> We were ask to add this change before build pdfs:
> **PR Fix Activating Additional Metrics:** #51
> Could we merge the PR 51 first, then rebase `GoebelL-patch-2` on `master` and rebuild the Sys Operator pdf?

Honestly I prefer to merge this first. Since PR 51 is one line change it's easier and more save IMHO to rebase the PR 51 branch  and carry over this line to Word and PDF.

**Review by chaconpiza — APPROVED** [review]

**Pull request merged**
